"""empty message

Revision ID: e5ad643c7dba
Revises: 2f92ea86c43c
Create Date: 2019-09-25 22:03:47.501499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ad643c7dba'
down_revision = '2f92ea86c43c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('homepage_link', sa.String(length=120), nullable=True))
    op.drop_column('artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artist', 'homepage_link')
    op.drop_column('artist', 'address')
    # ### end Alembic commands ###
